image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%QTDIR%\bin;%PATH%

build_script:
  - qmake HelloQt.pro
  - nmake