configuration: Debug
platform: x64
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%QTDIR%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - qmake HelloQt.pro
  - nmake